title: bus-ticketing-website
email: imran.kuet14@gmail.com
description: A bus booking website
baseurl: "bus-ticketing-website"
url: ""
twitter_username: jekyllrb
github_username: jekyll

markdown:kramdown
theme:minima
plugins: - jekyll-feed